### ISSUE TITLE
Old go-ethereum branch cloned => Golang v1.10 does not work

### ISSUE THREAD

**Issue by ChrisKru97** [MainframeHQ/onyx#60]
https://github.com/MainframeHQ/onyx/blob/51b143a713c5bf2ccb5144ce5bed6e86602ef6ae/scripts/build_binaries.sh#L29
https://github.com/MainframeHQ/go-ethereum/blob/568f99f2e173f7c3ffae575ea74a07fa0741121f/build/ci.go#L179

It validates golang v1.10 as older than v1.07, in newer branches of go-ethereum it is fixed

**Comment by howleysv** [comment]
Thanks @ChrisKru97, I can confirm that our upcoming prototype release will use a geth version containing the fix 👍
