### ISSUE TITLE
Cant find any guidance on compiling and running Onyx.

### ISSUE THREAD

**Issue by Uzair1995** [MainframeHQ/onyx#76]
I liked your idea and work on Onyx and also watched the demo at Devcon 3. Currently I am trying to run your testnet release v5 on testnet, but I cant find a way to successfully work with this. It prompts to start the local server and when I do that it shows that I need to stake 1 MFT. I have searched everywhere but cant find a solution. Also there are no forums or communities where I can ask these questions. I know its not any codding issue or may be but please help. Also the documentation does not help in any case.

**Comment by howleysv** [comment]
We have updated our release to use mainnet MFT tokens and updated the UX so the flow should work better now.
