### ISSUE TITLE
Improve the Mainframe Staking NUX (Make whitelisted ETH address "frozen")

### ISSUE THREAD

**Issue by philiparthurmoore** [MainframeHQ/onyx#81]
This is what's shown on Step 2 of the **Stake Mainframe Token** screen in Onyx:

<img width="800" alt="2018-07-11_12-52-20" src="https://user-images.githubusercontent.com/28684/42553069-764c9020-8509-11e8-88ab-603175fc5918.png">

This is problematic for two reasons:

1. It doesn't explain anywhere that users should not change that ETH address. 
2. It doesn't prevent users from changing that ETH address. 

I propose that you either:

1. Put clear instructions on that screen or
2. (Preferred) Make that field "frozen" such that people cannot edit that ETH address. 

Or a combination of the two. Right now it's not super-clear and I sent off MFT to an ETH address of my choosing, thinking that I would be able to do so given the current UI. 

Thanks!

**Comment by philiparthurmoore** [comment]
Note that I do see this in the README, but if there's a signup flow, I assume that all relevant instructions are in the actual client, not inside of a README.

> NOTE: do not alter the auto-generated address in the grey box. This will submit another transaction to MyCrypto, this time to perform the actual deposit so that your node can be allowed to use the Mainframe network.

**Comment by philiparthurmoore** [comment]
<img width="800" alt="2018-07-11_13-05-02" src="https://user-images.githubusercontent.com/28684/42553424-0c200928-850b-11e8-98a4-4cbcdf2106db.png">

**Comment by howleysv** [comment]
Thanks for the feedback @philiparthurmoore!

We have updated the staking flow a bit to make it a little more user friendly, so we've locked the ETH address field and added some checks in to monitor the progress of the 2 transactions inside the app.

**Comment by philiparthurmoore** [comment]
Thanks! Looks like that was taken care of here: https://github.com/MainframeHQ/onyx/pull/82/commits/30fd4ed68a9e35a5b86fd58d0df32097d5277923

Cheers. 🙇🏽‍♂️
