### ISSUE TITLE
Tried going through staking flow to start local Onyx server, got transaction error

### ISSUE THREAD

**Issue by cloudonshore** [MainframeHQ/onyx#83]
https://etherscan.io/tx/0x3a367a1294c5ed1efe2aaa9b1c7e31b818a511d080c5b3ca8e2f7e0a9b1a49b3

**Comment by howleysv** [comment]
Thanks for the feedback @cloudonshore 

It seems like it failed because you didn't have >1 MFT token in the wallet you were using for staking. This seems like something we should check during the staking flow to warn the user if there is not enough MFT to perform the staking transaction.
