### ISSUE TITLE
Awaiting transaction to be mined

### ISSUE THREAD

**Issue by brdtpro** [MainframeHQ/onyx#84]
![image](https://user-images.githubusercontent.com/30812522/42929853-f3c01d34-8b43-11e8-8330-89d20eb48e27.png)
I send 1 MFT a long time ago, but application didn't work. What is the reason?

**Comment by howleysv** [comment]
Hi @brdtpro, are you still having the issue? Did you check etherscan to see if the transaction was mined?

**Comment by brdtpro** [comment]
![image](https://user-images.githubusercontent.com/30812522/43194333-c511e3c0-900a-11e8-8933-80d196ee0b30.png)
the problem remains the same, though the transaction is confirmed. Sent a few pieces, but nothing new.
https://etherscan.io/tx/0xe9b259bab93be54e56b74f01c93bce89a210e41f9068de639a50f6600cb97c4c

**Comment by howleysv** [comment]
Ah, this is the same issue as a number of other users encountered that will need to be fixed with better instructions/documentation - apologies!

When you open the link to mycrypto, you need to leave all the fields prefilled (including the 0 ETH amount) and submit the transaction as is. Manually changing it to 1 MFT will override the call to the staking contract.

**Comment by Squishy47** [comment]
I am Having the same issue,
I did not change any of the prefilled fields and the transaction has been confirmed yet i am still not able to start a local node.

**Comment by howleysv** [comment]
Hi @Squishy47 
What are you seeing in the app when it opens?
If you link me to the transaction on etherscan I can take a look.

**Comment by Squishy47** [comment]
Hi, @howleysv ,
ether scan link - https://etherscan.io/tx/0xedb54a60498600e2771aa663546a72b68f5dbe2948ea1946de9db0f8ef5e20bc

the default screen when opening the app.
![screen shot 2018-08-15 at 11 45 34 am](https://user-images.githubusercontent.com/19436976/44144770-bd38dd1c-a080-11e8-9aef-0888afaebbd9.png)

**Comment by howleysv** [comment]
The way that the staking process works is in 2 steps. The first transaction lets you approve the staking contract to take 1 MFT from your wallet. Then you must submit a second transaction to the staking contract to whitelist your address (and in the process, it transfers 1 MFT from your wallet).

So, there are 2 things that you'll need to do.
1. There are currently no MFT in the wallet that you linked above, so you will need to transfer at least 1 MFT to this wallet, or start again with a different wallet that has some MFT.
2. Continue the staking flow by entering your wallet address in the box in the screenshot you sent, it should recognise that step 1 has already been completed and prompt you to submit the second transaction.

Then it should work for you.

You should check out the video we put on our blog showing step-by-step how to stake in onyx: https://blog.mainframe.com/how-to-stake-your-own-mft-in-onyx-d892c72b86a1
We also have a telegram testing group where people have been trying out onyx and helping each other get set up: https://t.me/mainframetesting
